### ISSUE TITLE
ここはreturn if params[:status_event].nil? || %w[start complete pend].include?(params[:status_event])でいいかも？

### ISSUE THREAD

**Issue by shibatadaiki** [o-t-k-t/incremental_todo#47]
https://github.com/o-t-k-t/incremental_todo/blob/878bcaf48c5a22ee083296ef7042fd9be5766557/app/controllers/tasks_controller.rb#L110

**Comment by o-t-k-t** [comment]
自分も別の箇所で1行にまとめて書いていたんですが、SG様レビュー時に「最近は後置ifには長い条件は書かないのが流行り」との指摘がありこの書き方となっております。。
